apiVersion: v1
kind: Secret
metadata:
  name: wikiread-secrets
  namespace: wikiread
type: Opaque
stringData:
  SECRET_KEY: "replace-me"
  DATABASE_URL: "postgresql://wiki_user:replace-me@wikiread-db.xxxxxx.eu-west-2.rds.amazonaws.com:5432/wikiread"
