apiVersion: v1
kind: Service
metadata:
  name: wikiread-preview
  namespace: wikiread
spec:
  type: ClusterIP
  selector:
    app: wikiread
  ports:
    - name: http
      port: 80
      targetPort: 8000
